import os

NOT_SET: object = object()
DEFAULT_INI_PATH: str = os.environ.get(
    'NETSUITE_CONFIG',
    os.path.expanduser('~/.config/netsuite.ini'),
)
DEFAULT_INI_SECTION: str = 'netsuite'

FACTORIES = [
    "Core",
    "CoreTypes",
    "FaultsTypes",
    "Faults",
    "Messages",
    "Common",
    "CommonTypes",
    "Scheduling",
    "SchedulingTypes",
    "Communication",
    "CommunicationTypes",
    "Filecabinet",
    "FilecabinetTypes",
    "Relationships",
    "RelationshipsTypes",
    "Support",
    "SupportTypes",
    "Accounting",
    "AccountingTypes",
    "Sales",
    "SalesTypes",
    "Purchases",
    "PurchasesTypes",
    "Customers",
    "CustomersTypes",
    "Financial",
    "FinancialTypes",
    "Bank",
    "BankTypes",
    "Inventory",
    "InventoryTypes",
    "General",
    "Customization",
    "CustomizationTypes",
    "Employees",
    "EmployeesTypes",
    "Website",
    "WebsiteTypes",
    "EmployeesTransactions",
    "EmployeesTransactionsTypes",
    "Marketing",
    "MarketingTypes",
    "DemandPlanning",
    "DemandPlanningTypes",
    "SupplyChain",
    "SupplyChainTypes",
]

URN_AS_ARGS = [
    ("core", "platform"),
    ("types.core", "platform"),
    ("types.faults", "platform"),
    ("faults", "platform"),
    ("messages", "platform"),
    ("common", "platform"),
    ("types.common", "platform"),
    ("scheduling", "activities"),
    ("types.scheduling", "activities"),
    ("communication", "general"),
    ("types.communication", "general"),
    ("filecabinet", "documents"),
    ("types.filecabinet", "documents"),
    ("relationships", "lists"),
    ("types.relationships", "lists"),
    ("support", "lists"),
    ("types.support", "lists"),
    ("accounting", "lists"),
    ("types.accounting", "lists"),
    ("sales", "transactions"),
    ("types.sales", "transactions"),
    ("purchases", "transactions"),
    ("types.purchases", "transactions"),
    ("customers", "transactions"),
    ("types.customers", "transactions"),
    ("financial", "transactions"),
    ("types.financial", "transactions"),
    ("bank", "transactions"),
    ("types.bank", "transactions"),
    ("inventory", "transactions"),
    ("types.inventory", "transactions"),
    ("general", "transactions"),
    ("customization", "setup"),
    ("types.customization", "setup"),
    ("employees", "lists"),
    ("types.employees", "lists"),
    ("website", "lists"),
    ("types.website", "lists"),
    ("employees", "transactions"),
    ("types.employees", "transactions"),
    ("marketing", "lists"),
    ("types.marketing", "lists"),
    ("demandplanning", "transactions"),
    ("types.demandplanning", "transactions"),
    ("supplychain", "lists"),
    ("types.supplychain", "lists"),
]
