import os

NOT_SET: object = object()
DEFAULT_INI_PATH: str = os.environ.get(
    'NETSUITE_CONFIG',
    os.path.expanduser('~/.config/netsuite.ini'),
)
DEFAULT_INI_SECTION: str = 'netsuite'

NAMESPACES = [
    "ns0",
    "ns1",
    "ns2",
    "ns3",
    "ns4",
    "ns5",
    "ns6",
    "ns7",
    "ns8",
    "ns9",
    "ns10",
    "ns11",
    "ns12",
    "ns13",
    "ns14",
    "ns15",
    "ns16",
    "ns17",
    "ns18",
    "ns19",
    "ns20",
    "ns21",
    "ns22",
    "ns23",
    "ns24",
    "ns25",
    "ns26",
    "ns27",
    "ns28",
    "ns29",
    "ns30",
    "ns31",
    "ns32",
    "ns33",
    "ns34",
    "ns35",
    "ns36",
    "ns37",
    "ns38",
    "ns39",
    "ns40",
    "ns41",
    "ns42",
    "ns43",
    "ns44",
    "ns45",
]

FACTORIES = [
    "Core",
    "CoreTypes",
    "FaultsTypes",
    "Faults",
    "Messages",
    "Common",
    "CommonTypes",
    "Scheduling",
    "SchedulingTypes",
    "Communication",
    "CommunicationTypes",
    "Filecabinet",
    "FilecabinetTypes",
    "Relationships",
    "RelationshipsTypes",
    "Support",
    "SupportTypes",
    "Accounting",
    "AccountingTypes",
    "Sales",
    "SalesTypes",
    "Purchases",
    "PurchasesTypes",
    "Customers",
    "CustomersTypes",
    "Financial",
    "FinancialTypes",
    "Bank",
    "BankTypes",
    "Inventory",
    "InventoryTypes",
    "General",
    "Customization",
    "CustomizationTypes",
    "Employees",
    "EmployeesTypes",
    "Website",
    "WebsiteTypes",
    "EmployeesTransactions",
    "EmployeesTransactionsTypes",
    "Marketing",
    "MarketingTypes",
    "DemandPlanning",
    "DemandPlanningTypes",
    "SupplyChain",
    "SupplyChainTypes",
]

URN_AS_ARGS = [
    ("core", "platform"),
    ("types.core", "platform"),
    ("types.faults", "platform"),
    ("faults", "platform"),
    ("messages", "platform"),
    ("common", "platform"),
    ("types.common", "platform"),
    ("scheduling", "activities"),
    ("types.scheduling", "activities"),
    ("communication", "general"),
    ("types.communication", "general"),
    ("filecabinet", "documents"),
    ("types.filecabinet", "documents"),
    ("relationships", "lists"),
    ("types.relationships", "lists"),
    ("support", "lists"),
    ("types.support", "lists"),
    ("accounting", "lists"),
    ("types.accounting", "lists"),
    ("sales", "transactions"),
    ("types.sales", "transactions"),
    ("purchases", "transactions"),
    ("types.purchases", "transactions"),
    ("customers", "transactions"),
    ("types.customers", "transactions"),
    ("financial", "transactions"),
    ("types.financial", "transactions"),
    ("bank", "transactions"),
    ("types.bank", "transactions"),
    ("inventory", "transactions"),
    ("types.inventory", "transactions"),
    ("general", "transactions"),
    ("customization", "setup"),
    ("types.customization", "setup"),
    ("employees", "lists"),
    ("types.employees", "lists"),
    ("website", "lists"),
    ("types.website", "lists"),
    ("employees", "transactions"),
    ("types.employees", "transactions"),
    ("marketing", "lists"),
    ("types.marketing", "lists"),
    ("demandplanning", "transactions"),
    ("types.demandplanning", "transactions"),
    ("supplychain", "lists"),
    ("types.supplychain", "lists"),
]
